data:extend(
{
    {
        type = "recipe",
        name = "basic-metal-scrap-smelting-foundry",
        icon= "__space-age__/graphics/icons/fluid/molten-iron.png",
        icon_size = 64,
        category = "metallurgy",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "basic-metal-scrap", amount = 10}},
        results = {{type="fluid", name="molten-iron", amount=25},
                    {type="fluid", name="molten-copper", amount=25}}
    },
    {
        type = "recipe",
        name = "advanced-metal-scrap-smelting-foundry",
        icon= "__space-age__/graphics/icons/fluid/molten-iron.png",
        icon_size = 64,
        category = "metallurgy",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "advanced-metal-scrap", amount = 10}},
        results = {{type="fluid", name="molten-iron", amount=75},
                    {type="fluid", name="molten-copper", amount=75}}
    },
    {
        type = "recipe",
        name = "electronic-scrap-smelting-foundry",
        icon= "__space-age__/graphics/icons/fluid/molten-iron.png",
        icon_size = 64,
        category = "metallurgy",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "electronic-scrap", amount = 10}},
        results = {{type="fluid", name="molten-iron", amount=50},
                    {type="fluid", name="molten-copper", amount=50}}
    },
    {
        type = "recipe",
        name = "basic-metal-scrap-recycle-chemical",
        icon= "__base__/graphics/icons/iron-plate.png",
        icon_size = 64,
        category = "chemistry",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "basic-metal-scrap", amount = 10},
                        {type = "fluid", name = "sulfuric-acid", amount=30}},
        results = {{type="item", name="iron-plate", amount=3, probability=0.5},
                    {type="item", name="copper-plate", amount=3, probability=0.5}}
    },
    {
        type = "recipe",
        name = "derust-iron",
        icon= "__base__/graphics/icons/iron-plate.png",
        icon_size = 64,
        category = "chemistry",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "rusted-iron-plate", amount = 1},
                        {type = "fluid", name = "sulfuric-acid", amount=10}},
        results = {{type="item", name="iron-plate", amount=1, probability=0.95}},
    },
    {
        type = "recipe",
        name = "derust-copper",
        icon= "__base__/graphics/icons/copper-plate.png",
        icon_size = 64,
        category = "chemistry",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "rusted-copper-plate", amount = 1},
                        {type = "fluid", name = "sulfuric-acid", amount=10}},
        results = {{type="item", name="copper-plate", amount=1, probability=0.95}},
    },
    {
        type = "recipe",
        name = "derust-steel",
        icon= "__base__/graphics/icons/steel-plate.png",
        icon_size = 64,
        category = "chemistry",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "rusted-steel-plate", amount = 1},
                        {type = "fluid", name = "sulfuric-acid", amount=10}},
        results = {{type="item", name="steel-plate", amount=1, probability=0.95}},
    },
    {
        type = "recipe",
        name = "basic-metal-scrap-recycle",
        icon= "__base__/graphics/icons/iron-plate.png",
        icon_size = 64,
        category = "recycling",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "basic-metal-scrap", amount = 1}},
        results = {{type="item", name="iron-plate", amount=1, probability=0.2},
                    {type="item", name="copper-plate", amount=1, probability=0.2}}
    },
    {
        type = "recipe",
        name = "oil-scrap-recycle-chemical",
        icon= "__base__/graphics/icons/fluid/heavy-oil.png",
        icon_size = 64,
        category = "oil-processing",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "oil-scrap", amount = 10},
                        {type = "fluid", name = "steam", amount = 50}},
        results = {{type="fluid", name="heavy-oil", amount=50},
                    {type="item", name="carbon", amount=1, probability=0.4}}
    },
    {
        type = "recipe",
        name = "electronic-scrap-recyle",
        icon= "__space-age__/graphics/icons/scrap.png",
        icon_size = 64,
        category = "recycling",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "electronic-scrap", amount = 1}},
        results = {{type="item", name="iron-plate", amount=1, probability=0.2},
                    {type="item", name="copper-wire", amount=1, probability=0.2}}
    },
    {
        type = "recipe",
        name = "basic-electronic-scrap-to-green-circuit",
        icon= "__base__/graphics/icons/electronic-circuit.png",
        icon_size = 64,
        category = "electronics-or-assembling",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "electronic-scrap", amount = 10}},
        results = {{type="item", name="electronic-circuit", amount=2}}
    },
    {
        type = "recipe",
        name = "basic-electronic-scrap-to-red-circuit",
        icon= "__base__/graphics/icons/advanced-circuit.png",
        icon_size = 64,
        category = "electromagnetics",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "electronic-scrap", amount = 10},
                        {type = "item", name = "plastic-bar", amount = 10}},
        results = {{type="item", name="advanced-circuit", amount=3}}
    },
    {
        type = "recipe",
        name = "advanced-metal-scrap-foundry-tungsten-carbide",
        icon= "__space-age__/graphics/icons/tungsten-carbide.png",
        icon_size = 64,
        category = "metallurgy",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "advanced-metal-scrap", amount = 10},
                        {type = "fluid", name = "sulfuric-acid", amount = 50},
                        {type = "item", name = "carbon", amount = 2}},
        results = {{type="item", name="tungsten-carbide", amount = 2}}
    },
    {
        type = "recipe",
        name = "advanced-metal-scrap-foundry-tungsten-plate",
        icon= "__space-age__/graphics/icons/tungsten-plate.png",
        icon_size = 64,
        category = "metallurgy",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "advanced-metal-scrap", amount = 10},
                        {type = "fluid", name = "sulfuric-acid", amount = 50},
                        {type = "fluid", name = "molten-iron", amount = 20}},
        results = {{type="item", name="tungsten-plate", amount = 2}}
    },
    {
        type = "recipe",
        name = "advanced-metal-scrap-foundry-holmium",
        icon= "__space-age__/graphics/icons/fluid/holmium-solution.png",
        icon_size = 64,
        category = "metallurgy",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "advanced-metal-scrap", amount = 10},
                        {type = "fluid", name = "sulfuric-acid", amount = 50}},
        results = {{type="fluid", name="holmium-solution", amount = 40}}
    },
    {
        type = "recipe",
        name = "advanced-metal-scrap-foundry-lithium",
        icon= "__space-age__/graphics/icons/lithium-plate.png",
        icon_size = 64,
        category = "metallurgy",
        energy_required = 5,
        subgroup = "scrap-processing",
        ingredients = {{type = "item", name = "advanced-metal-scrap", amount = 10},
                        {type = "fluid", name = "sulfuric-acid", amount = 50},
                        {type = "fluid", name = "holmium-solution", amount = 20}},
        results = {{type="item", name="lithium-plate", amount = 2}}
    },
}
)